# Generated by Django 3.2.7 on 2021-09-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaci', models.CharField(max_length=4)),
                ('iata', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('grados_longitud', models.FloatField(default=0)),
                ('grados_latitud', models.FloatField(default=0)),
                ('altitud', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=3)),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aeropuertos.aeropuerto')),
            ],
        ),
    ]
