# Generated by Django 3.2.7 on 2021-10-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buscador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vuelo', models.IntegerField()),
                ('duracion', models.CharField(max_length=20)),
                ('disponibilidad', models.IntegerField(default=0)),
                ('fecha_salida', models.DateField(auto_now_add=True)),
                ('fecha_llegada', models.DateField(auto_now_add=True)),
                ('aeropuerto_origen', models.CharField(max_length=3)),
                ('aeropuerto_destino', models.CharField(max_length=3)),
                ('paradas', models.IntegerField(default=0)),
                ('oneway', models.BooleanField(default=False)),
                ('precio_base', models.FloatField()),
                ('precio_total', models.FloatField()),
                ('aerolinea', models.CharField(max_length=3)),
            ],
        ),
    ]
