# Generated by Django 3.2.7 on 2021-10-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aeropuertos', '0001_initial'),
        ('Buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscador',
            name='aeropuerto_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Aeropuertos.aeropuerto'),
        ),
        migrations.AlterField(
            model_name='buscador',
            name='aeropuerto_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Aeropuertos.aeropuerto'),
        ),
    ]
