# Generated by Django 3.2.7 on 2021-10-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0002_auto_20210930_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buscador',
            old_name='id_vuelo',
            new_name='id_ruta',
        ),
    ]
