# Generated by Django 3.2.7 on 2021-10-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0003_rename_id_vuelo_buscador_id_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscador',
            name='fecha_llegada',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buscador',
            name='fecha_salida',
            field=models.CharField(max_length=50),
        ),
    ]
