# Generated by Django 3.2.7 on 2021-09-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vuelo', models.IntegerField()),
                ('nombre_pasajero', models.CharField(max_length=50)),
                ('apellido_pasajero', models.CharField(max_length=50)),
                ('fecha_nacimiento_pasajero', models.DateField()),
                ('telefono_pasajero', models.CharField(max_length=10)),
                ('email_pasajero', models.CharField(max_length=80)),
            ],
        ),
    ]
