# Generated by Django 3.2.7 on 2021-10-04 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aeropuertos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTiquete', models.IntegerField(default=0)),
                ('id_ruta', models.IntegerField()),
                ('duracion', models.CharField(max_length=20)),
                ('disponibilidad', models.IntegerField(default=0)),
                ('fecha_salida', models.CharField(max_length=50)),
                ('fecha_llegada', models.CharField(max_length=50)),
                ('paradas', models.IntegerField(default=0)),
                ('oneway', models.BooleanField(default=False)),
                ('precio_base', models.FloatField()),
                ('precio_total', models.FloatField()),
                ('aerolinea', models.CharField(max_length=200)),
                ('idUsuario', models.CharField(max_length=200)),
                ('mombreUsuario', models.CharField(max_length=200)),
                ('apellidoUsuario', models.CharField(max_length=200)),
                ('nVuelo', models.CharField(max_length=200)),
                ('nPasajeros', models.CharField(max_length=200)),
                ('aeropuerto_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Aeropuertos.aeropuerto')),
                ('aeropuerto_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Aeropuertos.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPago', models.IntegerField(default=0)),
                ('fechaCompra', models.DateTimeField()),
                ('estadoCompra', models.BooleanField()),
                ('idTiquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkout.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infopago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkout.pago')),
                ('inforuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkout.voucher')),
            ],
        ),
    ]
